# Уникальный ключ вашего проекта в SonarQube
sonar.projectKey=Quantum

# Путь к исходным файлам (относительно корня проекта)
sonar.sources=src

# Язык проекта (например, java, js, py)
sonar.language=js

# URL вашего сервера SonarQube
sonar.host.url=http://localhost:9000

# Токен, который вы скопировали ранее
sonar.login=sqp_8b90bcc08ef32adcd70ec0d08823503611ad4ed0